name: Node.JS CI/CD

on: 
  push: 
    branches: [main]

Jobs: 
  test:
  
    name: Test
    runs-on: ubuntu-latest
    
    strategy: 
      node-version: [10.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0

      - name: Use Node JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-verion: ${{ matrix.node-version }}

      - name: NPM install, build and test
        run: |
          npm install 
          npm test
        env: 
          DBHOST: ${{ secrets.DBHOST }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}